spring:
  application:
    name: chapter_05

  datasource:
    url: jdbc:mysql://localhost:3306/board_service
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: board_account
      password: board_account
  jpa:
    hibernate:
      ddl-auto: validate
